services:
  emotions_backend:
    build: ./emotions_app
    container_name: emotions_backend_hf
    restart: unless-stopped

    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - huggingface_cache:/models/huggingface
    networks:
      - backend_net

volumes:
  huggingface_cache:

networks:
  backend_net:
    driver: bridge